<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PC-liangxuqing" name="com.xyuan.ngtest.ps.test.usercenter1" tests="1" failures="0" timestamp="23 Oct 2017 07:46:43 GMT" time="0.454" errors="1">
  <testcase name="favfocusgroupTest" time="0.454" classname="com.xyuan.ngtest.ps.test.usercenter1">
    <error type="java.lang.AssertionError" message="
Expected: a string containing &quot;\&quot;msg\&quot;:\&quot;名称已存在\&quot;}&quot;
     but: was &quot;{&quot;sta&quot;:1,&quot;data&quot;:0,&quot;msg&quot;:&quot;可以使用&quot;}&quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "\"msg\":\"名称已存在\"}"
     but: was "{"sta":1,"data":0,"msg":"可以使用"}"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.xyuan.ngtest.MyAssert.MyAssert.asserting(MyAssert.java:12)
	at com.xyuan.ngtest.process.ExecuteFactory.createExecute(ExecuteFactory.java:61)
	at com.xyuan.ngtest.ps.test.usercenter1.favfocusgroupTest(usercenter1.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- favfocusgroupTest -->
</testsuite> <!-- com.xyuan.ngtest.ps.test.usercenter1 -->
