<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-liangxuqing" name="usercenter" tests="1" failures="1" timestamp="23 Oct 2017 07:46:43 GMT" time="0.499" errors="0">
  <testcase name="favfocusgroupTest" time="0.454" classname="com.xyuan.ngtest.ps.test.usercenter1">
    <failure type="java.lang.AssertionError" message="
Expected: a string containing &amp;quot;\&amp;quot;msg\&amp;quot;:\&amp;quot;名称已存在\&amp;quot;}&amp;quot;
     but: was &amp;quot;{&amp;quot;sta&amp;quot;:1,&amp;quot;data&amp;quot;:0,&amp;quot;msg&amp;quot;:&amp;quot;可以使用&amp;quot;}&amp;quot;">
      <![CDATA[java.lang.AssertionError: 
Expected: a string containing "\"msg\":\"名称已存在\"}"
     but: was "{"sta":1,"data":0,"msg":"可以使用"}"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
	at com.xyuan.ngtest.MyAssert.MyAssert.asserting(MyAssert.java:12)
	at com.xyuan.ngtest.process.ExecuteFactory.createExecute(ExecuteFactory.java:61)
	at com.xyuan.ngtest.ps.test.usercenter1.favfocusgroupTest(usercenter1.java:38)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- favfocusgroupTest -->
</testsuite> <!-- usercenter -->
